language: node_js
node_js:
  - "node"

deploy:
  provider: firebase
  token:
    secure: Zr0KdTRTcvL70+LO5EeYaorcNBUrGdc8aNcWo8KEr/jx+aYD3FV+6hexf+bJ4JMdo+eez3c67umDoE0Hbkugee4lN44kW1tlr037c45GgkrWWfKwve70gkpQPdeSN0N5W8N1i+4VWeTjnsxq3g1qFrTd+TIHuJdA0XXyzSkDGlYaSC6S1xOlorlgzRnnepwGAztgr8VBCMUPlXga4Wbn5Ghy1PH9zIwPvlmo0yjD490eJJw9crRFK6jNgeQrqEvzLjaAczNEYgqh9oUZT9MUtM9CtSXpBtSsHfupSHurltQtaoS5vvEVs+EZ+hQ+mvyoExWTyAXWCkQYQ5aJtMHQZ2dgVRmoBf0u2J4u4C44frFUJadGbCm0kXpqEHzf45jcj2klirL2lWr6CRTu0E1XUkiQJtxC95ysmI7gQWxHa9Macs+EEfb9p+qyA4Rsx8Ibv9AUiB/RvZRkYMevVjfqY+IIgPly9qu4sZhy+QQS0wu/PfOAFh1FsCvoFFCP6u8OX3XnYU3TZOB/ZTI0kRYPzY9R2CBnpiaBrDEexZziskOco16BLsyB0AnlxFoTXEupW1C7zPRqjQbk5ZFhSQ5c7E+eSiRmye0IjqkgJ97t7RcI0zAz7CxZNjZC17IaBZnaIZ6hV7VdyMuuJ3WJe4eX1VqVAlWweQ/57Yd4K88mHb8=
  project: travelperk-f88f5

cache:
  directories:
    - node_modules