language: node_js
node_js:
  - node

branches:
  only:
    master

env:
  secure: DpDMdMXkJ/rOZ7OyUpourj0RMCL7fTY4AZXWmxSigVQLPEZ9TeE42TZ+vbfM9dd4yMmgL2iwQ/9zhvkK4n8mGUszYU1aiKcyrDqjpXDMT+vqNcu0BlD+bI/r3T0M/UPKDHvy8COmxr6OSGdWHvmhTA5bVFW2FiTxsce85I/wASOUP7Km8eu+Ut3gzOwX72g03odp6MRMFhZ9Y9k5RFTJvSlgfjDw3hXKGsHCJ/Vi6PWrfDBeN9g0IsvQgB7fC2vFcUpJ5u18M7NEC++voqkV+DtR51KxrQrvl2ckbpCjUHHwADTwfqyYIER0zHE7yB8JgoPewHXwZijbI/QXTiC0GN701YfQIp+55qlKgpstjmia2nYZNsPNPzlrpl2exovO4BKaC9qey9TsRO25hcRZYE4EK3meE0qm1FXs4B59geYEy6I4XQUVPMZjPR86T3X8I3uzLPYDsxZYOtw0TcGC/brih7RdK2VTeJKNl1aoTmDWDciuBRa09tqwNueFgO/+yFNgmjjYPwvq1uz2eEI/Me83DYxs6c6d1+cfNqjPx94kf3r1HHQQVM0ncvwWZ2ICMpzutxzqX85A6i7gB51C8OIIXBCY7KcGGEeCuSXXzqq3umCpRI04hTO7QGQ9qvP8pYj5/2chEPIB8ag3y7q2UoRxiYg/EErDMQ+05bRII+Q=

before_script:
  - npm install -g react-scripts
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

cache:
  directories:
    - node_modules
